name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.contents.outputs.data}}
      
 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          echo installing packages
          python -m pip install --upgrade pip
          pip install requests
          pip install flake8 pytest
          pip install pandas
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        id: contents
        run: |
          python 1.py
          contents=$(cat sample.json)
          echo"::set-output name=data::$contents"

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "new-json-file.json"
          json: ${{ steps.contents.outputs.data}}
